version: '3.3'
services:
  web_ng:
    image: heroku_project_web_ng
    build:
       context: . 
       dockerfile: Dockerfile_ng
    ports:
      - "4200:4200"
    depends_on:
      - web
      - db
    volumes:
      - ./angular_heroku_project:/app
  
  web:
    image: heroku_project_web
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    env_file:
      - docker.env
    command: bash scripts/run_on_docker.sh
    volumes:
      - .:/app
      - maven_repository:/root/.m2

  elasticsearch:
    image: elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    volumes:
      - elastic_search:/usr/share/elasticsearch/data

  db:
    image: "postgres:13-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
    driver: local
  maven_repository:
    driver: local
  elastic_search:
    driver: local
  

